tasks:
  # 1. install doppler
  # 2. download the development env files
  # 3. install and use node 18
  # 4. install dependencies
  - init: |
      brew install dopplerhq/cli/doppler
      doppler secrets download --token $DOPPLER_DEVELOPMENT_TOKEN_WEBSITE --no-file --format env >  ./source-code/website/.env
      nvm i 18.12
      nvm use 18.12
      nvm alias default 18.12
      npm install
    # using doppler run to set env variables automatically
    # the DOPPLER_DEVELOPMENT_SERVICE_KEY is set in gitpod's UI
    command: npm run dev

ports:
  - name: "@inlang/website"
    port: 3000
    onOpen: notify

github:
  prebuilds:
    addBadge: true

vscode:
  extensions:
    - aaron-bond.better-comments
    - "usernamehw.errorlens"
    - "mhutchie.git-graph"
    - "yzhang.markdown-all-in-one"
    - "bierner.markdown-preview-github-styles"
    - "bierner.markdown-mermaid"
    - "pkief.material-icon-theme"
    - "bradlc.vscode-tailwindcss"
    - "esbenp.prettier-vscode"
