
tasks:
  - init: npm install && npm run build
    # use node 18
    before: |
      nvm i 18.12
      nvm use 18.12
      nvm alias default 18.12
    command: npm run dev

vscode:
  extensions:
    - aaron-bond.better-comments
    - "usernamehw.errorlens"
    - "mhutchie.git-graph"
    - "yzhang.markdown-all-in-one"
    - "bierner.markdown-preview-github-styles"
    - "bierner.markdown-mermaid"
    - "pkief.material-icon-theme"
    - "bradlc.vscode-tailwindcss"
