tasks:
  # 1. install doppler and set token
  # 2. install and use node 18
  # 3. install dependencies
  - init: |
      brew install dopplerhq/cli/doppler
      echo $DOPPLER_DEVELOPMENT_SERVICE_KEY | doppler configure set token
      nvm i 18.12
      nvm use 18.12
      nvm alias default 18.12
      npm install
    # using doppler run to set env variables automatically
    # the DOPPLER_DEVELOPMENT_SERVICE_KEY is set in gitpod's UI
    command: doppler run -- npm run dev

ports:
  - name: "@inlang/website"
    port: 3000
    onOpen: notify

github:
  prebuilds:
    addBadge: true

vscode:
  extensions:
    - aaron-bond.better-comments
    - "usernamehw.errorlens"
    - "mhutchie.git-graph"
    - "yzhang.markdown-all-in-one"
    - "bierner.markdown-preview-github-styles"
    - "bierner.markdown-mermaid"
    - "pkief.material-icon-theme"
    - "bradlc.vscode-tailwindcss"
    - "esbenp.prettier-vscode"
