packages: 
  - "lix/source-code/*"
  - "inlang/source-code/*"
  - "inlang/source-code/plugins/*"
  - "inlang/source-code/message-lint-rules/*"
  - "inlang/source-code/versioned-interfaces/*"
  - "placeholder-company/source-code/*"