name: Bug report for `inlang.com`
description: Something is not working as expected on the `inlang.com` website
title: '[bug] <title>'
labels:
  - 'type: bug'
  - 'scope: website'
assignees:
  - NilsJacobsen
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: link
    attributes:
      label: 'On what page did you encounter the bug?'
      placeholder: 'https://inlang.com/...'
  - type: textarea
    id: bug-description
    attributes:
      label: Problem
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: fix-description
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a description so we can reproduce the problem you ran into
      placeholder: |
        # 1. Go to '...'
        # 2. Click on '....'
        # 3. ...
    validations:
      required: true
  - type: input
    id: browser-info
    attributes:
      label: System Info
      description: Which browser and version do you use?
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 'Other information'
      description: Do you have additional information that could help us fix the bug? Please include it here.
