blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/inlang/inlang/discussions
    about: Please ask and answer questions here.
  - name: Discord Chat
    url: https://discord.gg/WUhmpYhq
    about: Come chat with us on discord.