name: Auto format code to avoid merge conflicts

on:
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci

      - run: npm run format

      - name: commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: autofix lint issues"
