name: Continuous Integration

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Doppler CLI for env (public) variables
        uses: dopplerhq/cli-action@v2

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'pnpm'

      - run: pnpm run fetchPublicEnv && pnpm run ci
        if: ${{ env.DOPPLER_CI_ENV_TOKEN == '' }}
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_CI_ENV_TOKEN }}

      - run: doppler run -- pnpm run ci
        if: ${{ env.DOPPLER_CI_ENV_TOKEN != '' }}
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_CI_ENV_TOKEN }}
