name: Continuous Integration

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Doppler CLI for env (public) variables
        uses: dopplerhq/cli-action@v2

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: doppler run -- pnpm run ci
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_CI_ENV_TOKEN }}
