name: Test editor with E2E tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        browser: [chrome, firefox]
        version: [18]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"
          
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          start: npm run production
          wait-on: 'http://localhost:3000'
          parallel: true
          

