name: Test ide-extension with E2E tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest is disabled because build.js is not compatible
        version: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: pnpm install

      - name: Run e2e tests on normal platforms
        if: startsWith(matrix.os, 'ubuntu')
        run: xvfb-run -a pnpm --filter vs-code-extension run test:e2e

      - name: Run e2e tests on alien platforms
        if: startsWith(matrix.os, 'ubuntu') == false
        run: pnpm --filter vs-code-extension run test:e2e
