name: Test ide-extension with E2E tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install --no-save

      - name: Run e2e tests on normal platforms
        if: startsWith(matrix.os, 'ubuntu')
        run: xvfb-run -a npm run test:e2e -w vs-code-extension

      - name: Run e2e tests on alien platforms
        if: startsWith(matrix.os, 'ubuntu') == false
        run: npm run test:e2e -w vs-code-extension
