name: Test ide-extension with E2E tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run e2e tests on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: xvfb-run -a npm run test:e2e -w vs-code-extension

      - name: Run e2e tests on MacOS
        if: startsWith(matrix.os, 'macos')
        run: npm run test:e2e -w vs-code-extension

      - name: Run e2e tests on Windows
        if: startsWith(matrix.os, 'windows')
        shell: bash
        run: |
          npm config set script-shell "$(which bash)"
          npm run test:e2e -w vs-code-extension
