name: Links (Fail Fast)

on:
    push:
        branches:
          - "main"

    schedule:
      - cron: 0 0 1 * * # run monthly

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Markdown files
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
          args: --verbose --no-progress './*/documentation/**/*.md' './*/blog/**/*.md' './README.md' './*/README.md'
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'

      # inlang.com 
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        env:
            TARGET: htps://inlang.com
            RECURSIVE: true
            EXCLUDE_EXTERNAL_LINKS: true
            TITLE: Broken link found (${URL})
            BODY: |
              ## Broken link found

              Broken Link Checker found a broken link on ${TARGET}
        
              Target: ${URL}
              > ${REASON}

              [View Actions Results](https://github.com/${OWNER}/${REPO}/commit/${SHA}/checks)
            GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
