name: Lint Code

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm install --no-save

      - name: run formatters
        run: npm run format:fix

      - name: run linters
        run: npm run lint:fix

      - name: run link checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress './documentation/**/*.md' './README.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: run inlang lint
        run: npx @inlang/cli@latest lint

      - name: commit & push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: autofix lint issues'